version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstore_user
      MYSQL_PASSWORD: bookstore_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bookstore_net

  flaskapp:
    build: .
    restart: always
    environment:
      - FLASK_ENV=development
      - DB_HOST=database-objective-2.c9wuu22ec2ri.us-east-1.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASS=Salinitrato10.
      - DB_NAME=bookstore
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - /mnt/efs:/mnt/efs  # Monta el EFS en el contenedor
    networks:
      - bookstore_net

volumes:
  db_data:

networks:
  bookstore_net:

